### ISSUE TITLE
estimacion de costos

### ISSUE THREAD

**Issue by CarlosSD16** [SistemasTecTlaxiaco/estimacion-de-costos-entrevista-tr#1]
[reporte de costos.pdf](https://github.com/SistemasTecTlaxiaco/estimacion-de-costos-entrevista-tr/files/7571386/reporte.de.costos.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
